
- name: Clone VM to ESXi
  hosts: localhost
  collections:
    - community.vmware
  tasks:
    - name: Instant Clone a VM
      community.vmware.vmware_guest_instant_clone:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        folder: "TE VMs"
        datastore: "{{ te_username }}"
        datacenter: "{{vcenter_datacenter}}"
        host: "{{ vcenter_esxi_host }}"
        name: "{{ te_username }}"
        parent_vm: "Te-Desktop-VM"
        resource_pool: "{{vcenter_resource_pool}}"
        state: powered-on
      register: vm_clone
      delegate_to: localhost

    - debug:
        var: vm_clone