- name: Create Datastore
  hosts: localhost
  collections:
    - community.vmware
  tasks:
    - name: Gather info from vCenter about cluster
      community.vmware.vmware_cluster_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        cluster_name: '{{vcenter_cluster_name}}'
        validate_certs: false
      delegate_to: localhost
      register: cluster_info
#
#    - name: Mount VMFS datastores to ESXi
#      community.vmware.vmware_host_datastore:
#        hostname: '{{ vcenter_hostname }}'
#        username: '{{ vcenter_username }}'
#        password: '{{ vcenter_password }}'
#        datastore_name: '{{ vcenter_datastore_name }}'
#        datastore_type: '{{ vcenter_datastore_type }}'
#        vmfs_device_name: '{{vcenter_datastore_naa}}'
#        vmfs_version: 6
#        esxi_hostname: '{{ inventory_hostname }}'
#        validate_certs: false
#        state: present
#      delegate_to: localhost