- name: Create Datastore
  hosts: localhost
  collections:
    - community.vmware
  tasks:
    - name: Gather info from vCenter about cluster
      community.vmware.vmware_cluster_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        cluster_name: '{{vcenter_cluster_name}}'
        validate_certs: false
      delegate_to: localhost
      register: cluster_info
    - debug:
        var: cluster_info

    - name: "Set cluster_info for workflow"
      set_stats:
        data:
          cluster_info: "{{ cluster_info }}"

    - name: "first_host variable"
      set_fact:
        first_host: "{{cluster_info['clusters'][vcenter_cluster_name]['hosts'][0]['name']}}"

    #    - name: Debug Auto tags
    #      debug:
    #        msg: "{{ item['name'] }}"
    #      loop: "{{ cluster_info['clusters'][vcenter_cluster_name]['hosts'] }}"
    #      when: item.name == "{{vcenter_cluster_name}}"
    #      register: tagExists


    - debug:
        var: "{{ first_host }}"
    - debug:
        msg: "{{ first_host }}"

    - name: Mount VMFS datastores to ESXi
      community.vmware.vmware_host_datastore:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datastore_name: '{{ vcenter_datastore_name }}'
        datastore_type: 'vmfs'
        vmfs_device_name: '{{vcenter_datastore_naa}}'
        vmfs_version: 6
        esxi_hostname: '{{ item.name }}'
        validate_certs: false
        state: present
      loop: "{{cluster_info['clusters'][vcenter_cluster_name]['hosts']}}"

