
- name: Rescan HBAs
  hosts: localhost
  collections:
    - community.vmware
  tasks:
  - name: Rescan HBA's for a given ESXi host and refresh storage system objects
    community.vmware.vmware_host_scanhba:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        refresh_storage: true
        validate_certs: false
        cluster_name: '{{ vcenter_cluster_name }}'
    delegate_to: localhost